version: 0.2

phases:
  install:
    commands:
      - apt-get update
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./dist/angular-devops s3://angular-code-deploy --acl 'public-read' --delete

artifacts:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
  discard-paths: yes
  base-directory: 'dist/angular-devops'